version: '3'

services:

  # Proxy for ssl termination and easier hostname access
  # SSL certificates with the virtual host name need to be added to ./data/ssl
  proxy:
    build:
      context: ./docker
      dockerfile: Dockerfile.nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./data/ssl/:/etc/nginx/certs
    environment:
      DHPARAM_BITS: 2048
      DHPARAM_GENERATION: "false"
      HTTPS_METHOD: "noredirect"
      HSTS: "off"
    depends_on:
      - nextcloud
    networks:
      default:
        aliases:
          - nextcloud${DOMAIN_SUFFIX}
          - nextcloud2${DOMAIN_SUFFIX}
          - nextcloud3${DOMAIN_SUFFIX}
          - stable16${DOMAIN_SUFFIX}
          - stable17${DOMAIN_SUFFIX}
          - stable18${DOMAIN_SUFFIX}
          - collabora${DOMAIN_SUFFIX}
          - onlyoffice${DOMAIN_SUFFIX}
          - collabora2${DOMAIN_SUFFIX}
          - proxy${DOMAIN_SUFFIX}

  haproxy:
    image: haproxy
    expose:
      - 80
    environment:
      VIRTUAL_HOST: "proxy${DOMAIN_SUFFIX}"
    volumes:
      - ./docker/configs/haproxy.conf:/usr/local/etc/haproxy/haproxy.cfg:ro

  nextcloud:
    build:
      context: ./docker
      dockerfile: Dockerfile.php72
    environment:
      # SQL: 'sqlite'
      # SQL: 'mysql'
      SQL: 'pgsql'
      NEXTCLOUD_AUTOINSTALL: "YES"
      NEXTCLOUD_AUTOINSTALL_APPS:
      WITH_REDIS: "YES"
      VIRTUAL_HOST: "nextcloud${DOMAIN_SUFFIX}"
      HTTPS_METHOD: "noredirect"
      ADDITIONAL_APPS_PATH:
      NEXTCLOUD_TRUSTED_DOMAINS:
    volumes:
      - '${REPO_PATH_SERVER:-/home/auke/git/server}:/var/www/html'
      - data:/var/www/html/data
      - config:/var/www/html/config
      - '${ADDITIONAL_APPS_PATH:-./data/apps-extra}:/var/www/html/apps-extra'
      - /var/www/html/apps-writable
      - ./data/skeleton/:/skeleton
      - ./data/additional.config.php:/var/www/html/config/additional.config.php:ro
      - ./data/shared:/shared
    ports:
      - "${PORTBASE:-800}0:80"
    depends_on:
      #- database-mysql
      - database-postgres
      - redis
      - mail


  database-postgres:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: postgres
    expose:
      - 5432

  redis:
    image: redis:3

  mail:
    image: mailhog/mailhog
    environment:
      VIRTUAL_HOST: "mail${DOMAIN_SUFFIX}"
      VIRTUAL_PORT: 8025



volumes:
  data:
  config:
  document_data:
  document_log:
  objectstorage_fakes3:
  objectstorage_minio:
  smb:
  elasticsearch_data:

networks:
  default:
    ipam:
      driver: default
      config:
        - subnet: ${DOCKER_SUBNET:-192.168.21.0/24}
